name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00
  push:
    branches:
      - main
  

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}

      # Install the dependencies.
      - name: Install dependencies
        run: npm install

      # Run the tests.
      - name: Run tests
        run: npm test

      # Run the linter.
      - name: Run linter
        run: npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
